# This is a basic workflow to help you get started with Actions

name: VarianleDemo

# Controls when the action will run. 
on: [push]
env:
  user_name: "Prashanth"
  demo_name: "reddy"
  
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  VariableUsageJob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      job_var1: "job value variable"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Usine workflow_variable
        run:  echo Hello,$user_name!
              Welcome $demo_name!!
              Here is job variable $job_var1
              Here is step variable $step_var1
        env:
          step_var1: "I'm step variable"
      
